apiVersion: apps/v1
kind: Deployment

metadata:
  name: market-db
  namespace: market
spec:
  replicas: 1
  selector:
    matchLabels:
      app: market-db
  template:
    metadata:
      labels:
        app: market-db
    spec:
      containers:
        - name: market-db
          image: postgres:13-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres
      volumes:
        - name: postgres
          emptyDir: {}
